name: CI

permissions:
  checks: write
  contents: read
  pull-requests: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]
  workflow_dispatch:

env:
  NODE_ENV: test
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  UPSTASH_REDIS_REST_URL: ${{ secrets.UPSTASH_REDIS_REST_URL }}
  UPSTASH_REDIS_REST_TOKEN: ${{ secrets.UPSTASH_REDIS_REST_TOKEN }}

jobs:
  # Fast feedback with smoke tests
  smoke-tests:
    name: 🔥 Smoke Tests
    runs-on:
      - self-hosted
      - Linux
      - ARM64
    timeout-minutes: 5

    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v4

      - name: 🎯 Determine context
        id: context
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "check_name=Smoke Tests" >> $GITHUB_OUTPUT
            echo "is_pr=true" >> $GITHUB_OUTPUT
          else
            echo "check_name=Smoke Tests" >> $GITHUB_OUTPUT
            echo "is_pr=false" >> $GITHUB_OUTPUT
          fi

      - name: 📝 Create GitHub Check
        uses: ./.github/actions/github-check
        id: check_run
        with:
          check_name: ${{ steps.context.outputs.check_name }}
          action: create
          status: in_progress
          title: '🚧 Running critical path smoke tests...'
          summary: 'Validating essential functionality and basic interactions...'

      - name: 🔧 Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'

      - name: 📦 Install dependencies
        run: npm ci --legacy-peer-deps

      - name: 🔥 Run smoke tests
        id: smoke
        run: npm run test:smoke

      - name: ✅ Update Check on Success
        if: success()
        uses: ./.github/actions/github-check
        with:
          check_name: ${{ steps.context.outputs.check_name }}
          action: update
          check_run_id: ${{ steps.check_run.outputs.check_run_id }}
          status: completed
          conclusion: success
          title: '✅ Smoke tests passed'
          summary: |
            🎉 **Critical path validation successful!**

            All essential functionality is working correctly:
            - ✅ Homepage loads correctly
            - ✅ Navigation to customizer works
            - ✅ Basic UI components render
            - ✅ Core interactions functional

      - name: ❌ Update Check on Failure
        if: failure()
        uses: ./.github/actions/github-check
        with:
          check_name: ${{ steps.context.outputs.check_name }}
          action: update
          check_run_id: ${{ steps.check_run.outputs.check_run_id }}
          status: completed
          conclusion: failure
          title: '❌ Smoke tests failed'
          summary: |
            🚨 **Critical functionality is broken!**

            Essential features are not working. Check the [logs](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) immediately.

  # Main CI checks
  ci-checks:
    name: ✅ CI Checks
    runs-on:
      - self-hosted
      - Linux
      - ARM64
    timeout-minutes: 10
    needs: smoke-tests

    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v4

      - name: 🎯 Determine context
        id: context
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "check_name=CI Checks" >> $GITHUB_OUTPUT
            echo "is_pr=true" >> $GITHUB_OUTPUT
            echo "target_env=preview" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "check_name=CI Checks" >> $GITHUB_OUTPUT
            echo "is_pr=false" >> $GITHUB_OUTPUT
            echo "target_env=production" >> $GITHUB_OUTPUT
          else
            echo "check_name=CI Checks" >> $GITHUB_OUTPUT
            echo "is_pr=false" >> $GITHUB_OUTPUT
            echo "target_env=preview" >> $GITHUB_OUTPUT
          fi

      - name: 📝 Create GitHub Check
        uses: ./.github/actions/github-check
        id: check_run
        with:
          check_name: ${{ steps.context.outputs.check_name }}
          action: create
          status: in_progress
          title: '🚧 CI checks starting...'
          summary: 'Running linting, type checks, Jest tests, and build verification...'

      - name: 🔧 Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'

      - name: 📦 Install dependencies
        run: npm ci --legacy-peer-deps

      - name: 🔎 Lint code
        id: lint
        run: npm run lint

      - name: 🔍 TypeScript type check
        id: typecheck
        run: npm run type-check

      - name: 🧪 Run Jest tests with coverage
        id: test
        run: npm run test:coverage

      - name: 🏗️ Build application
        id: build
        run: npm run build

      - name: ✅ Verify build output
        id: verify
        run: |
          if [ ! -d ".next" ] && [ ! -d "dist" ] && [ ! -d "build" ]; then
            echo "❌ Build output directory not found"
            exit 1
          fi
          echo "✅ Build completed successfully"

      - name: 📊 Upload coverage (PR only)
        if: github.event_name == 'pull_request'
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./test-results/coverage/lcov.info
          directory: ./test-results/coverage/
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false

      - name: 📝 Generate step summary
        if: always()
        run: |
          echo "## CI Summary" >> $GITHUB_STEP_SUMMARY
          echo "| Step | Status |" >> $GITHUB_STEP_SUMMARY
          echo "|------|--------|" >> $GITHUB_STEP_SUMMARY
          echo "| Linting | ${{ steps.lint.outcome == 'success' && '✅ Passed' || '❌ Failed' }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Type Check | ${{ steps.typecheck.outcome == 'success' && '✅ Passed' || '❌ Failed' }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Jest Tests | ${{ steps.test.outcome == 'success' && '✅ Passed' || '❌ Failed' }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Build | ${{ steps.build.outcome == 'success' && '✅ Passed' || '❌ Failed' }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Verification | ${{ steps.verify.outcome == 'success' && '✅ Passed' || '❌ Failed' }} |" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Overall Status**: ${{ job.status }}" >> $GITHUB_STEP_SUMMARY
          echo "**Target Environment**: ${{ steps.context.outputs.target_env }}" >> $GITHUB_STEP_SUMMARY
          echo "**Run ID**: ${{ github.run_id }}" >> $GITHUB_STEP_SUMMARY

      - name: 📤 Upload build artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ci-build-artifacts-${{ github.run_id }}
          path: |
            .next/
            dist/
            build/
            test-results/
          retention-days: 7

      - name: ✅ Update Check on Success
        if: success()
        uses: ./.github/actions/github-check
        with:
          check_name: ${{ steps.context.outputs.check_name }}
          action: update
          check_run_id: ${{ steps.check_run.outputs.check_run_id }}
          status: completed
          conclusion: success
          title: '✅ All CI checks passed'
          summary: |
            ✅ **All CI checks passed successfully!**

            | Check | Status |
            |-------|--------|
            | Linting | ✅ Passed |
            | Type Check | ✅ Passed |
            | Jest Tests | ✅ Passed |
            | Build | ✅ Passed |
            | Verification | ✅ Passed |

            **Next steps:**
            ${{ github.event_name == 'pull_request' && '- E2E tests will run once Vercel preview deployment is ready' || '- Production deployment monitoring will begin' }}

      - name: ❌ Update Check on Failure
        if: failure()
        uses: ./.github/actions/github-check
        with:
          check_name: ${{ steps.context.outputs.check_name }}
          action: update
          check_run_id: ${{ steps.check_run.outputs.check_run_id }}
          status: completed
          conclusion: failure
          title: '❌ CI checks failed'
          summary: |
            ❌ **CI checks failed**

            **Failed steps:** ${{ steps.lint.outcome == 'failure' && 'Linting' || '' }} ${{ steps.typecheck.outcome == 'failure' && 'Type Check' || '' }} ${{ steps.test.outcome == 'failure' && 'Jest Tests' || '' }} ${{ steps.build.outcome == 'failure' && 'Build' || '' }} ${{ steps.verify.outcome == 'failure' && 'Verification' || '' }}

            **Next steps:**
            1. Check the [workflow logs](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) for detailed error messages
            2. Fix the issues locally
            3. Push your changes to re-run the checks

      - name: ⚠️ Update Check on Cancellation
        if: cancelled()
        uses: ./.github/actions/github-check
        with:
          check_name: ${{ steps.context.outputs.check_name }}
          action: update
          check_run_id: ${{ steps.check_run.outputs.check_run_id }}
          status: completed
          conclusion: cancelled
          title: '⚠️ CI checks cancelled'
          summary: 'The CI workflow was cancelled before completion.'

  # Core functionality tests (runs after CI)
  core-tests:
    name: 🧪 Core Tests
    runs-on:
      - self-hosted
      - Linux
      - ARM64
    timeout-minutes: 15
    needs: ci-checks
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/main'

    env:
      BASE_URL: http://localhost:3000

    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v4

      - name: 📝 Create GitHub Check
        uses: ./.github/actions/github-check
        id: check_run
        with:
          check_name: 'Core Tests'
          action: create
          status: in_progress
          title: '🧪 Running core functionality tests...'
          summary: 'Testing individual components and features...'

      - name: 🔧 Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'

      - name: 📦 Install dependencies
        run: npm ci --legacy-peer-deps

      - name: 🧪 Run core tests
        id: core
        run: npm run test:core

      - name: 📤 Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: core-test-results-${{ github.run_id }}
          path: test-results/playwright/
          retention-days: 7

      - name: ✅ Update Check on Success
        if: success()
        uses: ./.github/actions/github-check
        with:
          check_name: 'Core Tests'
          action: update
          check_run_id: ${{ steps.check_run.outputs.check_run_id }}
          status: completed
          conclusion: success
          title: '✅ Core tests passed'
          summary: |
            🎉 **All core functionality tests passed!**

            Component testing completed successfully:
            - ✅ Home page functionality
            - ✅ Customizer interface
            - ✅ Color picker operations
            - ✅ File upload handling
            - ✅ AI picker interactions
            - ✅ Image download features
            - ✅ Canvas rendering

      - name: ❌ Update Check on Failure
        if: failure()
        uses: ./.github/actions/github-check
        with:
          check_name: 'Core Tests'
          action: update
          check_run_id: ${{ steps.check_run.outputs.check_run_id }}
          status: completed
          conclusion: failure
          title: '❌ Core tests failed'
          summary: |
            ❌ **Core functionality tests failed**

            Check the [test results](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) for details.

  # Quality assurance tests (parallel with core tests)
  quality-tests:
    name: 🛡️ Quality Tests
    runs-on:
      - self-hosted
      - Linux
      - ARM64
    timeout-minutes: 20
    needs: ci-checks
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/main'

    env:
      BASE_URL: http://localhost:3000

    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v4

      - name: 📝 Create GitHub Check
        uses: ./.github/actions/github-check
        id: check_run
        with:
          check_name: 'Quality Tests'
          action: create
          status: in_progress
          title: '🛡️ Running quality assurance tests...'
          summary: 'Testing accessibility, performance, security, and responsive design...'

      - name: 🔧 Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'

      - name: 📦 Install dependencies
        run: npm ci --legacy-peer-deps

      - name: 🧪 Run quality tests
        id: quality
        run: npm run test:quality

      - name: 📤 Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: quality-test-results-${{ github.run_id }}
          path: test-results/playwright/
          retention-days: 7

      - name: ✅ Update Check on Success
        if: success()
        uses: ./.github/actions/github-check
        with:
          check_name: 'Quality Tests'
          action: update
          check_run_id: ${{ steps.check_run.outputs.check_run_id }}
          status: completed
          conclusion: success
          title: '✅ Quality tests passed'
          summary: |
            🎉 **All quality assurance tests passed!**

            Quality validation completed successfully:
            - ✅ Accessibility (WCAG compliance)
            - ✅ Performance benchmarks
            - ✅ Security validation
            - ✅ Responsive design

      - name: ❌ Update Check on Failure
        if: failure()
        uses: ./.github/actions/github-check
        with:
          check_name: 'Quality Tests'
          action: update
          check_run_id: ${{ steps.check_run.outputs.check_run_id }}
          status: completed
          conclusion: failure
          title: '❌ Quality tests failed'
          summary: |
            ❌ **Quality assurance tests failed**

            Quality issues detected. Check the [test results](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) for details.

  # API health checks (parallel with other tests)
  api-tests:
    name: 🌐 API Tests
    runs-on:
      - self-hosted
      - Linux
      - ARM64
    timeout-minutes: 10
    needs: ci-checks

    env:
      BASE_URL: http://localhost:3000
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      UPSTASH_REDIS_REST_URL: ${{ secrets.UPSTASH_REDIS_REST_URL }}
      UPSTASH_REDIS_REST_TOKEN: ${{ secrets.UPSTASH_REDIS_REST_TOKEN }}

    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v4

      - name: 📝 Create GitHub Check
        uses: ./.github/actions/github-check
        id: check_run
        with:
          check_name: 'API Tests'
          action: create
          status: in_progress
          title: '🌐 Running API health checks...'
          summary: 'Testing API endpoints and integration scenarios...'

      - name: 🔧 Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'

      - name: 📦 Install dependencies
        run: npm ci --legacy-peer-deps

      - name: 🧪 Run API tests
        id: api
        run: npm run test:api

      - name: 📤 Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: api-test-results-${{ github.run_id }}
          path: test-results/playwright/
          retention-days: 7

      - name: ✅ Update Check on Success
        if: success()
        uses: ./.github/actions/github-check
        with:
          check_name: 'API Tests'
          action: update
          check_run_id: ${{ steps.check_run.outputs.check_run_id }}
          status: completed
          conclusion: success
          title: '✅ API tests passed'
          summary: |
            🎉 **All API tests passed!**

            API validation completed successfully:
            - ✅ Health check endpoints
            - ✅ Integration scenarios
            - ✅ Error handling
            - ✅ Rate limiting

      - name: ❌ Update Check on Failure
        if: failure()
        uses: ./.github/actions/github-check
        with:
          check_name: 'API Tests'
          action: update
          check_run_id: ${{ steps.check_run.outputs.check_run_id }}
          status: completed
          conclusion: failure
          title: '❌ API tests failed'
          summary: |
            ❌ **API tests failed**

            API issues detected. Check the [test results](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) for details.
