name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci-pipeline:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test

    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v4

      - name: 🔧 Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'npm'

      - name: ♻️ Cache node_modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: 📦 Install all dependencies (including dev)
        run: npm install

      - name: 🔨 Build the project
        run: npm run build

      - name: 🧪 Run Jest tests with coverage
        run: npm run test:coverage

      - name: 📸 Install Playwright browsers
        run: npx playwright install --with-deps

      - name: 🧭 Run Playwright tests
        run: npx playwright test

      - name: 📤 Upload Playwright artifacts (screenshots, traces, videos)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-results
          path: test-results/
