name: CI

permissions:
  checks: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  repository_dispatch:
    types: [vercel.deployment.success]

env:
  NODE_ENV: test
  BASE_URL: ${{ github.event.client_payload.url }}
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  UPSTASH_REDIS_REST_URL: ${{ secrets.UPSTASH_REDIS_REST_URL }}
  UPSTASH_REDIS_REST_TOKEN: ${{ secrets.UPSTASH_REDIS_REST_TOKEN }}

jobs:
  ci-checks:
    if: github.event_name == 'repository_dispatch' && github.event.client_payload.environment == 'preview'
    name: ✅ ci-checks
    runs-on:
      - self-hosted
      - Linux
      - ARM64
    timeout-minutes: 10

    steps:
      - name: 🧪 Log GitHub context
        run: echo '${{ toJson(github) }}'

      - name: ⬇️ Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.git.sha }}

      - name: 🔧 Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'

      - name: 🚀 Report in_progress status
        uses: ./.github/actions/report-status
        with:
          check_name: ✅ ci-checks
          status: in_progress
          title: '🚧 CI In Progress'
          summary: 'Running linting, type checks, Jest tests, and build verification...'
          sha: ${{ github.event.client_payload.git.sha }}
          host: ${{ secrets.APP_HOST }}
          app_secret: ${{ secrets.INTERNAL_APP_SECRET }}

      - name: 📦 Install dependencies
        run: npm ci --legacy-peer-deps

      - name: 🔎 Lint code
        id: lint
        run: npm run lint

      - name: 🔍 TypeScript type check
        id: typecheck
        run: npm run type-check

      - name: 🧪 Run Jest tests with coverage
        id: test
        run: npm run test:coverage

      - name: 📊 Upload coverage reports
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false

      - name: 🏗️ Build application
        id: build
        run: npm run build

      - name: ✅ Verify build output
        id: verify
        run: |
          if [ ! -d ".next" ] && [ ! -d "dist" ] && [ ! -d "build" ]; then
            echo "❌ Build output directory not found"
            exit 1
          fi
          echo "✅ Build completed successfully"

      - name: 📝 Generate step summary
        if: always()
        run: |
          echo "## CI Summary" >> $GITHUB_STEP_SUMMARY
          echo "| Step | Status |" >> $GITHUB_STEP_SUMMARY
          echo "|------|--------|" >> $GITHUB_STEP_SUMMARY
          echo "| Linting | ${{ steps.lint.outcome == 'success' && '✅ Passed' || '❌ Failed' }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Type Check | ${{ steps.typecheck.outcome == 'success' && '✅ Passed' || '❌ Failed' }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Jest Tests | ${{ steps.test.outcome == 'success' && '✅ Passed' || '❌ Failed' }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Build | ${{ steps.build.outcome == 'success' && '✅ Passed' || '❌ Failed' }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Verification | ${{ steps.verify.outcome == 'success' && '✅ Passed' || '❌ Failed' }} |" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Overall Status**: ${{ job.status }}" >> $GITHUB_STEP_SUMMARY
          echo "**Run ID**: ${{ github.run_id }}" >> $GITHUB_STEP_SUMMARY

      - name: 📤 Upload build artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ci-build-artifacts
          path: |
            .next/
            dist/
            build/
            coverage/
          retention-days: 7

      # Unified status reporting for all outcomes
      - name: ✅ Report success
        if: always() && success()
        uses: ./.github/actions/report-status
        with:
          check_name: ✅ ci-checks
          status: completed
          conclusion: success
          title: '✅ CI Passed'
          summary: 'All linting, type checks, Jest tests, and build verification passed successfully.'
          sha: ${{ github.event.client_payload.git.sha }}
          host: ${{ secrets.APP_HOST }}
          app_secret: ${{ secrets.INTERNAL_APP_SECRET }}

      - name: ❌ Report failure
        if: always() && failure()
        uses: ./.github/actions/report-status
        with:
          check_name: ✅ ci-checks
          status: completed
          conclusion: failure
          sha: ${{ github.event.client_payload.git.sha }}
          host: ${{ secrets.APP_HOST }}
          app_secret: ${{ secrets.INTERNAL_APP_SECRET }}

      - name: ⚠️ Report cancelled
        if: always() && cancelled()
        uses: ./.github/actions/report-status
        with:
          check_name: ✅ ci-checks
          status: completed
          conclusion: cancelled
          sha: ${{ github.event.client_payload.git.sha }}
          host: ${{ secrets.APP_HOST }}
          app_secret: ${{ secrets.INTERNAL_APP_SECRET }}
