name: CI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  repository_dispatch:
    types: [vercel.deployment.success]

jobs:
  ci-checks:
    if: github.event_name == 'repository_dispatch' && github.event.client_payload.environment == 'preview'
    name: ✅ ci-checks
    runs-on:
      - self-hosted
      - Linux
      - ARM64
    timeout-minutes: 5

    env:
      NODE_ENV: test
      BASE_URL: ${{ github.event.client_payload.url }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      UPSTASH_REDIS_REST_URL: ${{ secrets.UPSTASH_REDIS_REST_URL }}
      UPSTASH_REDIS_REST_TOKEN: ${{ secrets.UPSTASH_REDIS_REST_TOKEN }}

    steps:
      - name: ✅ Mark check as in progress
        if: github.event_name == 'repository_dispatch' && github.event.client_payload.git.sha != ''
        uses: ./.github/actions/update-check
        with:
          sha: ${{ github.event.client_payload.git.sha }}
          name: '✅ ci-checks'
          status: 'in_progress'
          title: '⏳ CI Running'
          summary: 'The CI checks are currently in progress.'
          token: ${{ secrets.FGT_UPDATE_CHECK_TOKEN }}

      - name: ⬇️ Checkout code
        uses: actions/checkout@v4

      - name: 🔧 Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'

      - name: 📦 Install dependencies
        run: npm ci --legacy-peer-deps

      - name: 🔎 Lint code
        run: npm run lint

      - name: 🧪 Run Jest tests
        run: npm run test

      - name: ✅ Update check status to failed
        if: failure() && github.event_name == 'repository_dispatch' && github.event.client_payload.git.sha != ''
        uses: ./.github/actions/update-check
        with:
          sha: ${{ github.event.client_payload.git.sha }}
          name: '✅ ci-checks'
          status: 'completed'
          conclusion: 'failure'
          title: '❌ CI Failed'
          summary: 'Some checks failed. Review the logs for details.'
          token: ${{ secrets.FGT_UPDATE_CHECK_TOKEN }}
      - name: ✅ Update check status to success
        if: success() && github.event_name == 'repository_dispatch' && github.event.client_payload.git.sha != ''
        uses: ./.github/actions/update-check
        with:
          sha: ${{ github.event.client_payload.git.sha }}
          name: '✅ ci-checks'
          status: 'completed'
          conclusion: 'success'
          title: '✅ CI Passed'
          summary: 'All tests and lint checks passed successfully.'
          token: ${{ secrets.FGT_UPDATE_CHECK_TOKEN }}

      - name: ✅ Update check status to cancelled
        if: cancelled() && github.event_name == 'repository_dispatch' && github.event.client_payload.git.sha != ''
        uses: ./.github/actions/update-check
        with:
          sha: ${{ github.event.client_payload.git.sha }}
          name: '✅ ci-checks'
          status: 'completed'
          conclusion: 'cancelled'
          title: '⚠️ CI Cancelled'
          summary: 'The CI run was cancelled.'
          token: ${{ secrets.FGT_UPDATE_CHECK_TOKEN }}

      - name: ✅ Update check status to skipped
        if: github.job == 'ci-checks' && github.run_attempt > 1 && github.event_name == 'repository_dispatch' && github.event.client_payload.git.sha != ''
        uses: ./.github/actions/update-check
        with:
          sha: ${{ github.event.client_payload.git.sha }}
          name: '✅ ci-checks'
          status: 'completed'
          conclusion: 'skipped'
          title: '⚠️ CI Skipped'
          summary: 'The CI run was skipped due to a previous attempt.'
          token: ${{ secrets.FGT_UPDATE_CHECK_TOKEN }}

      - name: ✅ Update check status to timed_out
        if: failure() && github.event_name == 'repository_dispatch' && github.event.client_payload.git.sha != '' && contains(github.event.client_payload.git.message || '', 'timeout')
        uses: ./.github/actions/update-check
        with:
          sha: ${{ github.event.client_payload.git.sha }}
          name: '✅ ci-checks'
          status: 'completed'
          conclusion: 'timed_out'
          title: '⏰ CI Timed Out'
          summary: 'The CI run timed out before completion.'
          token: ${{ secrets.FGT_UPDATE_CHECK_TOKEN }}

  playwright-tests:
    if: github.event_name == 'repository_dispatch' && github.event.client_payload.environment == 'preview'
    name: 🧪 playwright-tests
    needs: ci-checks
    runs-on:
      - self-hosted
      - Linux
      - ARM64

    timeout-minutes: 35
    strategy:
      fail-fast: true
      matrix:
        project: [chromium, firefox, webkit]

    env:
      NODE_ENV: test
      BASE_URL: ${{ github.event.client_payload.url }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      UPSTASH_REDIS_REST_URL: ${{ secrets.UPSTASH_REDIS_REST_URL }}
      UPSTASH_REDIS_REST_TOKEN: ${{ secrets.UPSTASH_REDIS_REST_TOKEN }}
      VERCEL_AUTOMATION_BYPASS_SECRET: ${{ secrets.VERCEL_AUTOMATION_BYPASS_SECRET }}

    steps:
      - name: ✅ Mark check as in progress
        if: github.event_name == 'repository_dispatch' && github.event.client_payload.git.sha != ''
        uses: ./.github/actions/update-check
        with:
          sha: ${{ github.event.client_payload.git.sha }}
          name: 'playwright-tests (${{ matrix.project }})'
          status: 'in_progress'
          title: '⏳ Playwright Tests Running (${{ matrix.project }})'
          summary: 'The Playwright tests are currently in progress.'
          token: ${{ secrets.FGT_UPDATE_CHECK_TOKEN }}

      - name: ⬇️ Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.git.sha }}
          fetch-depth: 0

      - name: 🔧 Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'

      - name: 📦 Install dependencies
        run: |
          npm ci --legacy-peer-deps

      - name: 🧪 Run Playwright tests (${{ matrix.project }})
        run: npx playwright test --project=${{ matrix.project }} --reporter=list,html
        env:
          CI: true

      - name: ✅ Update check status to failed
        if: failure() && github.event_name == 'repository_dispatch' && github.event.client_payload.git.sha != ''
        uses: ./.github/actions/update-check
        with:
          sha: ${{ github.event.client_payload.git.sha }}
          name: 'playwright-tests (${{ matrix.project }})'
          status: 'completed'
          conclusion: 'failure'
          title: '❌ Playwright Tests Failed (${{ matrix.project }})'
          summary: 'Some Playwright tests failed. Review the logs for details.'
          token: ${{ secrets.FGT_UPDATE_CHECK_TOKEN }}

      - name: ✅ Update check status to success
        if: success() && github.event_name == 'repository_dispatch' && github.event.client_payload.git.sha != ''
        uses: ./.github/actions/update-check
        with:
          sha: ${{ github.event.client_payload.git.sha }}
          name: 'playwright-tests (${{ matrix.project }})'
          status: 'completed'
          conclusion: 'success'
          title: '✅ Playwright Tests Passed (${{ matrix.project }})'
          summary: 'All Playwright tests passed successfully.'
          token: ${{ secrets.FGT_UPDATE_CHECK_TOKEN }}

      - name: ✅ Update check status to cancelled
        if: cancelled() && github.event_name == 'repository_dispatch' && github.event.client_payload.git.sha != ''
        uses: ./.github/actions/update-check
        with:
          sha: ${{ github.event.client_payload.git.sha }}
          name: 'playwright-tests (${{ matrix.project }})'
          status: 'completed'
          conclusion: 'cancelled'
          title: '⚠️ Playwright Tests Cancelled (${{ matrix.project }})'
          summary: 'The Playwright tests run was cancelled.'
          token: ${{ secrets.FGT_UPDATE_CHECK_TOKEN }}

      - name: ✅ Update check status to skipped
        if: github.job == 'playwright-tests' && github.run_attempt > 1 && github.event_name == 'repository_dispatch' && github.event.client_payload.git.sha != ''
        uses: ./.github/actions/update-check
        with:
          sha: ${{ github.event.client_payload.git.sha }}
          name: 'playwright-tests (${{ matrix.project }})'
          status: 'completed'
          conclusion: 'skipped'
          title: '⚠️ Playwright Tests Skipped (${{ matrix.project }})'
          summary: 'The Playwright tests run was skipped due to a previous attempt.'
          token: ${{ secrets.FGT_UPDATE_CHECK_TOKEN }}

      - name: ✅ Update check status to timed_out
        if: failure() && github.event_name == 'repository_dispatch' && github.event.client_payload.git.sha != '' && contains(github.event.client_payload.git.message || '', 'timeout')
        uses: ./.github/actions/update-check
        with:
          sha: ${{ github.event.client_payload.git.sha }}
          name: 'playwright-tests (${{ matrix.project }})'
          status: 'completed'
          conclusion: 'timed_out'
          title: '⏰ Playwright Tests Timed Out (${{ matrix.project }})'
          summary: 'The Playwright tests run timed out before completion.'
          token: ${{ secrets.FGT_UPDATE_CHECK_TOKEN }}

      - name: 📤 Upload Playwright artifacts (screenshots, traces, videos)
        if: failure()
        continue-on-error: true
        uses: actions/upload-artifact@v4
        with:
          name: '${{ github.job }}-playwright-results-${{ matrix.project }}'
          path: test-results/
          retention-days: 7

      - name: 📤 Upload Playwright HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: '${{ github.job }}-playwright-html-report-${{ matrix.project }}'
          path: playwright-report
          retention-days: 7
