name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci-pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shard: [1, 2, 3, 4, 5]
    env:
      NODE_ENV: test
      BASE_URL: http://localhost:3000
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      UPSTASH_REDIS_REST_URL: ${{ secrets.UPSTASH_REDIS_REST_URL }}
      UPSTASH_REDIS_REST_TOKEN: ${{ secrets.UPSTASH_REDIS_REST_TOKEN }}

    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v4

      - name: 🔧 Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'npm'

      - name: ♻️ Cache node_modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: 📦 Install dependencies + Playwright browsers
        run: |
          npm install --legacy-peer-deps
          npx playwright install --with-deps

      - name: 🛠️ Install Chromium dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libnss3 \
            libatk-bridge2.0-0 \
            libx11-xcb1 \
            libxcomposite1 \
            libxdamage1 \
            libxrandr2 \
            libgbm1 \
            libgtk-3-0 \
            libasound2t64 \
            fonts-liberation

      - name: 🔎 Lint code
        run: npm run lint

      - name: 🔨 Build the project
        run: npm run build

      - name: 🚀 Start Next.js server
        run: |
          npm run start &
          npx wait-on http://localhost:3000

      - name: 🧭 Run Playwright tests (shard ${{ matrix.shard }}/5)
        run: npx playwright test --shard=${{ matrix.shard }}/5 --config=playwright.config.ts
        env:
          PLAYWRIGHT_TRACE: on
          PLAYWRIGHT_VIDEO: on

      - name: 🛑 Stop Next.js server
        if: always()
        run: kill $(lsof -t -i:3000) || true

      - name: 📤 Upload Playwright artifacts (screenshots, traces, videos)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-results
          path: test-results/
