name: Preview E2E Tests

permissions:
  checks: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  repository_dispatch:
    types: [vercel.deployment.success]

jobs:
  playwright-tests:
    if: github.event_name == 'repository_dispatch' && github.event.client_payload.environment == 'preview'
    name: 🧪 playwright-tests
    runs-on:
      - self-hosted
      - Linux
      - ARM64

    timeout-minutes: 35
    strategy:
      fail-fast: false
      matrix:
        project: [chromium, firefox, webkit]

    env:
      NODE_ENV: test
      BASE_URL: ${{ github.event.client_payload.url }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      UPSTASH_REDIS_REST_URL: ${{ secrets.UPSTASH_REDIS_REST_URL }}
      UPSTASH_REDIS_REST_TOKEN: ${{ secrets.UPSTASH_REDIS_REST_TOKEN }}
      VERCEL_AUTOMATION_BYPASS_SECRET: ${{ secrets.VERCEL_AUTOMATION_BYPASS_SECRET }}

    steps:
      - name: 🚀 Report playwright in_progress to GitHub App
        uses: ./.github/actions/report-checks
        with:
          sha: ${{ github.event.client_payload.git.sha }}
          status: in_progress
          name: playwright-tests (${{ matrix.project }})
          title: 🚧 E2E Tests In Progress (${{ matrix.project }})
          summary: Comprehensive end-to-end tests running on preview deployment...
          details_url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          host: ${{ secrets.APP_HOST }}
          app_secret: ${{ secrets.INTERNAL_APP_SECRET }}

      - name: 🧪 Log GitHub context
        run: echo '${{ toJson(github) }}'

      - name: ⬇️ Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.git.sha }}
          fetch-depth: 0

      - name: 🔧 Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'

      - name: 📦 Install dependencies
        run: npm ci --legacy-peer-deps

      - name: 🎭 Install Playwright browsers
        run: npx playwright install --with-deps

      - name: ⏳ Wait for preview deployment to be ready
        run: |
          echo "🔄 Waiting for preview deployment to be fully ready..."
          sleep 30
          echo "🧪 Testing preview URL: ${{ github.event.client_payload.url }}"
          curl -f ${{ github.event.client_payload.url }} || exit 1
          echo "✅ Preview deployment is ready!"

      - name: 🧪 Run Playwright E2E tests (${{ matrix.project }})
        run: npx playwright test --project=${{ matrix.project }} --reporter=list,html
        env:
          CI: true

      - name: 🔍 Run accessibility tests (${{ matrix.project }})
        run: npx playwright test --grep "@accessibility" --project=${{ matrix.project }}
        continue-on-error: true
        env:
          CI: true

      - name: ⚡ Run performance tests (${{ matrix.project }})
        run: npx playwright test --grep "@performance" --project=${{ matrix.project }}
        continue-on-error: true
        env:
          CI: true

      - name: ❌ Report playwright failure to GitHub App
        if: always() && failure()
        uses: ./.github/actions/report-checks
        with:
          sha: ${{ github.event.client_payload.git.sha }}
          status: completed
          conclusion: failure
          name: playwright-tests (${{ matrix.project }})
          title: ❌ E2E Tests Failed (${{ matrix.project }})
          summary: Some end-to-end tests failed on the preview deployment. Review the logs and artifacts for details.
          details_url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          host: ${{ secrets.APP_HOST }}
          app_secret: ${{ secrets.INTERNAL_APP_SECRET }}

      - name: ✅ Report playwright success to GitHub App
        if: always() && success()
        uses: ./.github/actions/report-checks
        with:
          sha: ${{ github.event.client_payload.git.sha }}
          status: completed
          conclusion: success
          name: playwright-tests (${{ matrix.project }})
          title: ✅ E2E Tests Passed (${{ matrix.project }})
          summary: All end-to-end tests passed successfully on the preview deployment. Ready for production!
          details_url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          host: ${{ secrets.APP_HOST }}
          app_secret: ${{ secrets.INTERNAL_APP_SECRET }}

      - name: ⚠️ Report playwright cancelled to GitHub App
        if: always() && cancelled()
        uses: ./.github/actions/report-checks
        with:
          sha: ${{ github.event.client_payload.git.sha }}
          status: completed
          conclusion: cancelled
          name: playwright-tests (${{ matrix.project }})
          title: ⚠️ E2E Tests Cancelled (${{ matrix.project }})
          summary: The end-to-end tests run was cancelled.
          details_url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          host: ${{ secrets.APP_HOST }}
          app_secret: ${{ secrets.INTERNAL_APP_SECRET }}

      - name: ⏰ Report playwright timed_out to GitHub App
        if: always() && failure() && contains(github.event.client_payload.git.message || '', 'timeout')
        uses: ./.github/actions/report-checks
        with:
          sha: ${{ github.event.client_payload.git.sha }}
          status: completed
          conclusion: timed_out
          name: playwright-tests (${{ matrix.project }})
          title: ⏰ E2E Tests Timed Out (${{ matrix.project }})
          summary: The end-to-end tests run timed out before completion.
          details_url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          host: ${{ secrets.APP_HOST }}
          app_secret: ${{ secrets.INTERNAL_APP_SECRET }}

      - name: 📤 Upload Playwright artifacts (screenshots, traces, videos)
        if: failure()
        continue-on-error: true
        uses: actions/upload-artifact@v4
        with:
          name: '${{ github.job }}-playwright-results-${{ matrix.project }}'
          path: test-results/
          retention-days: 7

      - name: 📤 Upload Playwright HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: '${{ github.job }}-playwright-html-report-${{ matrix.project }}'
          path: playwright-report
          retention-days: 7

      - name: 📝 Summary report for Playwright (${{ matrix.project }})
        if: always()
        run: |
          echo "## E2E Test Summary: ${{ matrix.project }}" >> $GITHUB_STEP_SUMMARY
          echo "🎭 Comprehensive tests finished running." >> $GITHUB_STEP_SUMMARY
          echo "- **Project**: ${{ matrix.project }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Preview URL**: ${{ github.event.client_payload.url }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Status**: ${{ job.status }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Run ID**: ${{ github.run_id }}" >> $GITHUB_STEP_SUMMARY
